### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [DimasSavchenko/Template-JWood#1]
1. Шрифты не подключились
1. А почему это не сгруппировать в один `<a>` ?
```
<a href="#contact"><p class="scroll__text color__white txt__up font__bold">do you want to see it with your own eyes? Scroll!</p></a>
<a href="#contact"><img src="img/scroll.png" alt="scroll"></a>
```
1. Если это БЭМ, то у footer'a нет класса `footer`
```
<footer id="contact">
<div class="footer__container">
```
1.  `mailto` для почты
1.  Структура проекта хромает, привыкни делать всё одинаково, например по вложениям вот:  
- id="about" class="about" `уникальный класс для того, чтобы повесить bg, по-умолчанию является display:block; width не надо`
-- container `контейнер одинаковый для всех блоков, является ограничителем контента по ширине`
--- какой-то уже контент

**Comment by DimasSavchenko** [comment]
1. Шрифты допотключил (2-м не правильно прописал путь).
2. Сгруппировал в одну ссылку.
3. Добавил класс футеру.
4. Добавил `mailto` к почте.
5. По поводу структуры проекта ещё есть вопросы.
